language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4'

cache:
  directories:
    - node_modules

branches:
  except:
    - gh-pages

before_script:
  - npm install -g codeclimate-test-reporter

script:
  - npm test
#after_script:
#  - npm codeclimatesend
